name: Download and cache

on: push

jobs:
  download-and-cache:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Install Tools
        run: |
          brew install coursier/formulas/coursier
          cs setup --yes
          brew install grype

      - name: Check version
        run: |
          sbt --version
