name: Download and cache

on: push

jobs:
  download-and-cache:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v4

#      - name: Set up Homebrew
#        uses: Homebrew/actions/setup-homebrew@master

      - name: Install Coursier
        run: |
          curl -fL https://github.com/coursier/coursier/releases/latest/download/cs-x86_64-pc-linux.gz | gzip -d > cs && chmod +x cs && ./cs setup --yes
          export PATH="/home/runner/local/share/coursier/bin"

          curl -sSfL https://raw.githubusercontent.com/anchore/grype/main/install.sh | sh -s -- -b /usr/local/bin
          echo $PATH
      #          brew install coursier/formulas/coursier
#          cs setup --yes
#          brew install grype

      
      

      - name: Check version
        run: |
          sbt --version
